### ISSUE TITLE
Demonic Gorilla plugin not updated to new hitsplash

### ISSUE THREAD

**Issue by Eelpan** [open-osrs/plugins#102]
Demonic gorilla plugin is not working with the new hitsplashes.

I sadly do not have knowledge to make a simple pull reuest, however i fixed it in my local version of runelite - simple as this : 
Replace all instances of "Hitsplat.HitsplatType.BLOCK" to "Hitsplat.HitsplatType.BLOCK_ME" within the plugin.

**Comment by xKylee** [comment]
As per your other request. We don’t support this plugin anymore, therefore it won’t be maintained and updated. Should you have asked in doscord you would have been told this

**Comment by Eelpan** [comment]
Oh, sorry. I thought the guy in the other thread just meant he / that section was not the correct place to request it. 
Thanks for reply - and awesome client btw :)
