### ISSUE TITLE
MES: Custom swap npc contact resets when shift is pressed

### ISSUE THREAD

**Issue by emiljensen2** [open-osrs/plugins#104]
If you use custom swaps to overwrite npc contact to the last npc option, then whenever you press shift it resets to cast and stays that way until you remove and re-add the custom swap.

It seems like the hotkey/shift swap for npc contact causes this bug, even if hotkey npc contact is disabled it still resets to cast upon pressing shift. Like it's messing with the menu entry even when disabled.

**Comment by xKylee** [comment]
i would suggest removing them from custom swaps, the whole point of this feature was to remove the need to do so.

**Comment by emiljensen2** [comment]
It doesn't remove the purpose of custom swaps. I have to hold shift in while using this new shift swap feature, I would like it to simply be left click. But as said despite the shift swap feature not being enabled it still checks the state and resets it upon pressing shift.

**Comment by xKylee** [comment]
As said, the shift click option was designed to remove the custom swaps. On shift click it will I register and remove the swap hence fuxking your custom swaps. There won’t be support for this if you run into issues
