### ISSUE TITLE
Puzzle box solver for clues is not working

### ISSUE THREAD

**Issue by immanualkantcode** [open-osrs/plugins#123]
![image](https://user-images.githubusercontent.com/20027771/76800413-fc678c80-67a9-11ea-9fdc-b8fb82c36205.png)

 I have only done master clues on the client so I cant say if it works or not for other tier clue scrolls. It does work on regular runelite for me.

**Comment by xKylee** [comment]
do you have puzzlesolver turned on at all? this would suggest you do not.
