### ISSUE TITLE
Unable to unmark objects

### ISSUE THREAD

**Issue by kruggles482** [open-osrs/plugins#145]
Marked a magic tree in my poh and have been unable to unmark it normally. Tried disabling and re-enabling plugin as well as restarting, no luck, Persisted for several days now.

**Comment by kruggles482** [comment]
I still can't unmark this dumb tree in my poh

**Comment by Dogyyblue** [comment]
Oh with the plugin that Mark's objects right, yes? Cause only way to remove it is going into the configs and removing it as of this moment. Been a bit broken when trying to remove stuff but adding it seems fine~

**Comment by xKylee** [comment]
fixed.
