### ISSUE TITLE
highlighted Ground items bug

### ISSUE THREAD

**Issue by Zo6** [open-osrs/plugins#155]
Hello i have noticed if i highlight one item lets say for example prayer potion(1)
which i used on maniacal monkeys , if i get a prayer potion drop fist time it will highlight it normaly
but after that it will only show the text on the ground with no item on the ground.
after that it will never show any highlighted item until i turn grounditem off then on again and it will work for few minutes and back again.

![](https://i.gyazo.com/7c727db14293ea1be09fb1726dc9840e.png)

![](https://i.gyazo.com/509c5aa8d4e006844f39fef240a00cfa.png)

**Comment by Zo6** [comment]
any news?

**Comment by xKylee** [comment]
#316
