### ISSUE TITLE
[bug] The Tmorph panel uses the wrong ids when you copy it

### ISSUE THREAD

**Issue by dayoshiguy** [open-osrs/plugins#205]
title

**Comment by xKylee** [comment]
by far, the worst issues ive ever seen, thanks so much for your help with this issue @dayoshiguy......


what id's are wrong? have you got examples of what they are and what they turn out to be when coppied? screenshots, steps to reproduce etc?

atm, this issue isnt even worth having open, next time, give us some info please.

**Comment by dayoshiguy** [comment]
Ok lol heres sum data:
i clicked the Set/Copy Active Morph plugin and the following ids were copied:
11850,24272:Head //should be 24271 for neitz faceguard not 24272
11852,24133:Cape 
6585,19555:Amulet //should be 19553 for torture ammy not 19555
11920,20999:Weapon //wrong id etc
11854,11832:Torso 
11856,18356:Legs //should be 11834
11858,22982:Hands
11860,14027:Boots //should be 13239 for prims
