### ISSUE TITLE
Chat translator conflicting with Key Remapping plugin

### ISSUE THREAD

**Issue by Demon-blood** [open-osrs/plugins#207]
After installing chat Translator whenever you hit ENTER to free up the chatbox to write, it causes your fps to drop all the way down till 1 fps and makes the entire client freeze.
I tried with backspace and this works just fine without any drops in fps.

I removed all plugins to make sure that no other plugin is conflicting, but it seems to only give this issue with Chat translator and Key Remapping enabled.

**Comment by Devtoon** [comment]
Howsit, I can't seem, to reproduce this issue. Is it still reoccurring?  If it is, include a little more information like logs and settings etc.

![9A0ivKgpoN](https://user-images.githubusercontent.com/66264581/85960889-f5eed080-b9a6-11ea-8164-60392399e0f9.gif)
