### ISSUE TITLE
Grand Exchange item stats display in wrong order

### ISSUE THREAD

**Issue by mileslay** [open-osrs/plugins#233]
RuneLite version 1.6.13
OpenOSRS version 3.3.1 nightly

When viewing the stats for the selected item in the Grand Exchange offer page, the item's stats are in the wrong order. Stab was moved the the bottom, instead of at the top.

![image](https://user-images.githubusercontent.com/11655672/81424148-1cb52700-911b-11ea-87ae-22f5c55b9462.png)

**Comment by xKylee** [comment]
this is resolved.
