### ISSUE TITLE
Remember last Tag Tab not compatible with Sync local instances

### ISSUE THREAD

**Issue by swazrgb** [open-osrs/plugins#253]
When both Remember last Tag Tab and Sync local instances are enabled, the bank tag is not remembered. To reproduce:

1. Start two clients configured with both settings enabled
2. Login on both
3. Leave one client idle, and open the bank on the other
4. With the bank open select a bank tag
5. Close the bank
6. Reopen the bank
7. Observe the bank tag was not remembered

Searching for `remember last tag tab` on discord will also show several other people running into this problem.

I suspect this happens because the remembered tag is stored in the `BankTagsConfig#tab`, which gets synced to the other clients as a config item. The plugin [updates this configuration every game tick](https://github.com/open-osrs/plugins/blob/master/banktags/src/main/java/net/runelite/client/plugins/banktags/BankTagsPlugin.java#L566-L569). which [can clear this config setting](https://github.com/open-osrs/plugins/blob/master/banktags/src/main/java/net/runelite/client/plugins/banktags/tabs/TabInterface.java#L507-L521).

Perhaps simply storing the last tab as a field in the `BankTagsPlugin` makes sense?

**Comment by redeems** [comment]
the purposed solution sounds fine to me, if it works, give it some testing then PR, ty for offering.
