### ISSUE TITLE
Ground Items - Sort by GE price issue

### ISSUE THREAD

**Issue by pawwe** [open-osrs/plugins#274]
I noticed that if "Sort by GE price" is enabled in "Ground Items" plugin it causes issues with the "Choose Option" right click options menu. If there are Feather, Raw chicken and Bones on the ground, the "Take Bones" option and "Walk here" will constantly changing places. If the Feather or Raw chicken is picked up, it stops.

Recorded a short video of the issue: https://imgur.com/a/dCLjotx

**Comment by pawwe** [comment]
If I remove "Bones" from the "Hidden Items" list, the "Sort by GE price" option seems to be working as expected. Maybe a fix could be that the hidden ground items should be ignored when sorting by GE price.

**Comment by Devtoon** [comment]
Howsit, currently having a look at this.

**Comment by Devtoon** [comment]
I can't seem to reproduce the issue and as far as I can see I'm using the same settings in the plugin as you are.

![test](https://user-images.githubusercontent.com/66264581/85902400-424ddb00-b804-11ea-8166-4b7efacc2907.gif)

Test again and let us know if it's still reoccurring. If it is you will need to provide more detail with logs and settings.

**Comment by pawwe** [comment]
Thanks for looking into this. I'm actually unable to reproduce this now. I'll close this ticket.
