### ISSUE TITLE
Hitsplat colorblind mode

### ISSUE THREAD

**Issue by Loh8372** [open-osrs/plugins#287]
Potentially add hitsplat recolor to resource packs to help in a "colorblind" mode for pvm'ing with friends.

**Comment by Devtoon** [comment]
Howsit, I started looking in to this but this requires a good understanding of color blindness. Even just recoloring a sprite for the different types of color blindness (never mind having some sort of intensity filter) is a challenge in itself. Hence why not even the official client supports it.

That said, if a ninja perhaps looks in to this maybe a good starting point could be the open source project [Color Oracle](https://colororacle.org/).

@Loh8372 I suggest in the interim if you're using Windows 10 then take a look at this [Color Filter in Windows 10](https://community.windows.com/en-us/stories/color-filter).
