### ISSUE TITLE
Clan Chat plugin only half working

### ISSUE THREAD

**Issue by danjsmith4** [open-osrs/plugins#318]
[https://i.imgur.com/xYl4fvW.png](url) to the picture, it is only half working plugin, wont show join/leave or show ranks in CC, if i download the newest client on first launch it works for 5 minutes, then stops working again. Sometimes when hopping worlds it will work for about 5 minutes again then go dead. I've tried removing from external manager, removing from launcher, no luck either.

**Comment by Lucwousin** [comment]
this was fixed in open-osrs/runelite#2705
