### ISSUE TITLE
suggestion : group screen markers (or nested screen markers)

### ISSUE THREAD

**Issue by runelt99** [open-osrs/plugins#323]
I often have a ton of them hidden and forget what i use them for and epecially that i can use several markers for a specfic purpose. This means that i keep making new ones over and over again. 

So i suggest allowing a super marker that once activated will activate several other markers. Idk if i explained it well enough.

**Comment by xKylee** [comment]
You can already “group” them by color which is more than enough. Even with a “master color” you still couldn’t have more than 1 color Marker on a Single Tile so this would be pointless.

**Comment by Lucwousin** [comment]
He's talking about screen markers, not tile markers
