### ISSUE TITLE
Suggestion - Add the option to make the report button display the exact time left until membership runs out

### ISSUE THREAD

**Issue by dayoshiguy** [open-osrs/plugins#324]
**Is your feature request related to a problem? Please describe.**
I never know when my membership will expire on the last day and sometimes don't have enough gp in my bank for a bond when it does.

**Describe the solution you'd like**
Add the option to make the report button display the exact time left until membership runs out by remembering the time you activated membership and doing some simple math.

**Describe alternatives you've considered**
You could maybe add this instead on the account options tab where it displays the days left.

**Additional context**
should be ok with yagex

**Comment by Devtoon** [comment]
Howsit,

I'm currently looking in to this.

@dayoshiguy do you mind providing a screenshot of where you suggest the membership time remaining should be displayed?

**Comment by xKylee** [comment]
implemented
