### ISSUE TITLE
"Unknown" room no longer working in CoX Scouter

### ISSUE THREAD

**Issue by JoeOSRS** [open-osrs/plugins#335]
Whitelisting/Blacklisting "Unknown" now has no effect when scouting for a CoX raid. It was working as expected yesterday morning/afternoon, I restarted my client at around 8PM GMT, after which the plugin no longer recognises "Unknown" or "unknown". 

The below screenshots are from a PC that had never had OpenOSRS installed on it, I done a fresh install just to check this issue wasn't something related to my previous settings/install.

![image](https://user-images.githubusercontent.com/67503239/85919921-4d862280-b867-11ea-9dfd-4118c88f5113.png)

An example of the same CoX layout but with other rooms whitelisted/blacklisted
![image](https://user-images.githubusercontent.com/67503239/85919933-67276a00-b867-11ea-8255-d0358d9d78b1.png)

**Comment by Lucwousin** [comment]
This is because it distinguishes between unknown combat and puzzle rooms. Change it to `Unknown (combat)` and/or `Unknown (puzzle)`

Nothing changed in the plugin, so you're probably misremembering this working.

**Comment by JoeOSRS** [comment]
This plugin doesn't distinguish between the two, when you first install it, it already comes with "unknown" in the blacklisted rooms options. 
Unknown (puzzle)/Unknown (combat)/unknown (puzzle)/unknown (combat) are all invalid inputs
![image](https://user-images.githubusercontent.com/67503239/85920247-11a08c80-b86a-11ea-9e07-621b54c5349d.png)
![image](https://user-images.githubusercontent.com/67503239/85920261-29781080-b86a-11ea-956e-86352ecbad4d.png)

**Comment by Lucwousin** [comment]
`	@ConfigItem(
		position = 27,
		titleSection = "roomConfig",
		keyName = "blacklistedRooms",
		name = "Blacklisted rooms",
		description = "Display blacklisted rooms in red on the overlay. Separate with comma (full name)",
		parse = true,
		clazz = Parse.class,
		method = "parse"
	)
	default String blacklistedRooms()
	{
		return "";
	}`

Looks like the input validation is wrong. The default "unknown" probably came from runelite's version of the plugin.
