### ISSUE TITLE
Menu Entries

### ISSUE THREAD

**Issue by SkrillexAkaCraft** [open-osrs/plugins#34]
By default "Game Objects' have Examine should be "Walk here"
By default "Players" have Follow should be "Walk here' except for PVP situations

**Comment by xKylee** [comment]
Sorry, I really don’t get what you’re getting at with this.

If you press hotkey to walk here it will always be walk here???

I’m assuming this is more of a feature request???

**Comment by SkrillexAkaCraft** [comment]
yes it will always be Walk here but it should be Walk here even whitout pressing the 'Shift' 

It used to be 'Walk here' before the update on everything not Follow or Examine

**Comment by xKylee** [comment]
So before the update it was “examine” on left click now it isn’t?

**Comment by SkrillexAkaCraft** [comment]
no before the update it was walk here and now it isn't same for the player issue it used to be walk here <player name> not follow <player name>

**Comment by xKylee** [comment]
This sounds like a problem with an unofficial plugin, as nothing we have done would have caused this. Please join the discord and talk in #discussion as what you’re expecting it to do isn’t normal behaviour and how it is now is the right behaviour
