### ISSUE TITLE
Alchemical Hydra respawn timer

### ISSUE THREAD

**Issue by Waldrin73** [open-osrs/plugins#341]
The ground timer on the Alchemical Hydra does not seem to work like other NPCs, maybe due to being instanced? I've got NPC Indicators enabled, with the Alchemical Hydra written into the list of NPCs to Highlight.

https://i.imgur.com/t04rQq6.png

**Comment by xKylee** [comment]
Try using *hydra*

Does this also occur on runelite?

Do you have any errors in your log?

**Comment by Waldrin73** [comment]
I tried * hydra * without spaces, but that does not seem to work either. Regardless of using Alchemical Hydra or * hydra*, the hydra is highlighted. Logs does not seem to be necessary as the plugin works, and the ground respawn timer works for most NPCs unlike the Alchemical Hydra.

**Comment by Lucwousin** [comment]
Looks like this is because `Actor::getWorldLocation` calls `WorldPoint::fromLocal` rather than `WorldPoint::fromLocalInstance`. Changing this _should_ be fine, but it's gonna need testing to see if it doesn't end up breaking something

**Comment by Waldrin73** [comment]
@xKylee
