### ISSUE TITLE
Issue: Interface Styles / Resource packs clash: Unable to use anything but default interface styles for Resource Packs

### ISSUE THREAD

**Issue by GrimWrath** [open-osrs/plugins#348]
@Owain94 
melkypie  - original author of resource packs

I am unable to use anything but default interface styles for Resource Packs.
I want to be able to use 2010 icons from interface styles with melkypie's resource packs. I was trying to see if I could use the assets from the 2010 interface styles source to overwrite those in the pack, but the plugin does not use any form of the assets at all.(Mainly icons like prayer, spellbook, inventory, etc) Not sure if I should let melkypie know as well.

Let me know what steps can be taken for this.

**Comment by xKylee** [comment]
You could always try creating your own resource pack using the 2010 icons....

**Comment by GrimWrath** [comment]
That's what I tried doing...Resource pack plugin does not support those icons...as I wrote in my original post...

**Comment by xKylee** [comment]
Ahh. In that case, your only option is to wait until it does support it (if it ever does).

I will also be closing this issue due to the resource pack not being from this repository.
