### ISSUE TITLE
Suggestion: Barbarian assault tick timer for every role

### ISSUE THREAD

**Issue by duspsc** [open-osrs/plugins#349]
Currently the defender role has the option to show the tick timer in barbarian assault. Seeing this timer would be useful as healer/attacker to easily know when poison ticks/ aggro changes occur. My suggestion is to move this tick timer to the 'general' section to make it available for every role, not just defender.

**Comment by Lucwousin** [comment]
For that poison thing you should check out the poison plugin. (now I think about it, that may not be that useful there cause using food on em and giving em a green hitsplat will make the plugin think it reset to 30 ticks)

There's still a timer in the plugin for call changes right?

**Comment by duspsc** [comment]
Yes you can use the call change timer to time your food usage. Seeing the tick timer itself(the one with only the numbers 0-9) would make it easier to put the food down at the same tick as the natural poison to speed up healing in niche situations.
