### ISSUE TITLE
menu entry swapper - puro puro wheat breaks stuff

### ISSUE THREAD

**Issue by runelt99** [open-osrs/plugins#353]
by having it on, instead of having walk here, it changes things to be first option - like any player has 'follow', clicking chat on cc mate will instantly 'add to friends' and implings i blacklisted are 'examine'

**Comment by ThatGamerBlue** [comment]
Side effect of this section https://github.com/open-osrs/plugins/blob/62245ebcb16731869f288a9ffd80f0f9cddd4550/menuentryswapper/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java#L450

**Comment by runelt99** [comment]
what is 'event.getopcode' ?

**Comment by xKylee** [comment]
It should only do this whilst in puro puro, however, not ideal

**Comment by tomcylke** [comment]
Instead of deprioritizing the walk entry shouldn't we just insert a new "push-through" entry that doesn't have its opcode incremented by 2000? That would make it the left click option without making left clicking on players follow them.
