### ISSUE TITLE
Player indicator "Highlight other players" does not work on attackable players in the wilderness

### ISSUE THREAD

**Issue by datashe12** [open-osrs/plugins#365]
Tested this on both nightly and stable.
I'm talking about this setting. https://i.imgur.com/Yhq4LsV.png
Attackable players in the wilderness just appear as a white dot with no name above their head rather than being highlighted as a red dot with red text above their head/on minimap.

**Comment by Macweese** [comment]
You're using the wrong setting... the one you want is probably the section above "[Target](https://i.imgur.com/WcisiUT.png)", not "Other"

**Comment by datashe12** [comment]
LOL that explains it, thanks for that
