### ISSUE TITLE
Runelite feature "Combat Level" when used in OpenOSRS, doesn't display the level range that can be hit or cant hit in the wilderness.

### ISSUE THREAD

**Issue by jonxsong** [open-osrs/plugins#388]
![T2INDprP25](https://user-images.githubusercontent.com/45381472/90161316-cffb7080-dd47-11ea-8eec-a34232079a5f.png)

**Comment by xKylee** [comment]
Try clicking reset, I’m in the wilderness right now and have the level range.

**Comment by jonxsong** [comment]
Just tried, still doesn't work? tried reinstalling combat level aswell.
