### ISSUE TITLE
Camera Outer Limit Broken

### ISSUE THREAD

**Issue by Kmichallik** [open-osrs/plugins#413]
The Camera Zoom Outer limit functionality no longer seems to work. Maxing it does not increase how far out you can zoom. The other functionality (vertical camera, right click moves camera, etc.) seems to work fine.

EDIT: the Camera Zoom version is 0.0.5 and I am using the Stable version of OpenOSRS.

**Comment by grian32** [comment]
Known, wait for upstream changes
