### ISSUE TITLE
Suggestion - Tile Indicators - option to mark intermediate tiles on player's path to destination tile

### ISSUE THREAD

**Issue by lappegl** [open-osrs/plugins#432]
Some mechanics in the game require very specific pathing, and while understanding how pathing works generally is enough to know how to do something like running the mazes in Sotetseg, one can't really immediately determine which specific tiles your character will be on when it comes to the tiles between your current position and target location.

For example, in Sepulchre, if you click down a long hall with floor traps on a few specific tiles, you need to know which tiles you will be touching to ensure you never touch the dangerous tile. This can sort of be done by marking a pair of "safe" start/destination tiles, but it would be helpful in some scenarios to see every tile you'll be on for any pathing situation.

Intermediate tiles could be outlined or shaded.

Example image:

![image](https://user-images.githubusercontent.com/35285044/94101580-c01a8600-fdf5-11ea-8ec3-1968d223a75f.png)

**Comment by tomcylke** [comment]
Someone should do this
https://oldschool.runescape.wiki/w/Pathfinding
It's basically just BFS with a couple of weird things
All of the work with collision flags has already been done in WorldArea

**Comment by ReeeMan** [comment]
I think pathfinder from the rlhub (repo already added in OPRS) already does this. 

https://github.com/Owain94/OpenOSRS-RL-hub/tree/master/pathfinder/src/main/java/com/pathfinder

**Comment by tomcylke** [comment]
I was unaware of this but I just downloaded it and tested it and the path it comes up with is wrong whenever there are any walls or obstacles involved. :/

**Comment by lappegl** [comment]
While the pathfinder plugin partially works, it will show each tile on the path between the current position and hovered tile. Also, as tomcylke points out, this highlighted path seems to ignore all obstacles as if you could no-clip to the destination.

What I'm asking for specifically is something that will mark the exact tiles I will touch on my way to my destination--not a path to a hovered tile, but the target destination of my current path.

Also, when running, your character will move 2 tiles at a time, so some tiles are "skipped" and not touched.

![image](https://user-images.githubusercontent.com/35285044/100043997-2c087300-2dd4-11eb-9bec-d263ee3af620.png)

Every tile is highlighted, but I only want to see 1) destination tile (red tile, already covered by Tile Indicators), 2) my current position (pink tile, already covered by Tile Indicators), and 3) intermediate tiles I will touch (yellow tiles--if I run to red, my pink position tile will only touch these yellow tiles).

It's part 3 that's missing.

While Pathfinder is useful for learning how the straight-then-diagonal pathing works and may be someone useful for beginners running Sotetseg mazes in TOB, the highlighted paths don't visually answer the question "which specific tiles will I touch on my path from my current position to my destination?"

**Comment by grian32** [comment]
Issues aren't for suggestions.
