### ISSUE TITLE
Thieving Plugin

### ISSUE THREAD

**Issue by billedwardz** [open-osrs/plugins#457]
Thieving plugin doesn't seem to be counting successful pickpockets on Vyres in Darkmeyer, only failed.

**Comment by xKylee** [comment]
Can you Post a screenshot of a successful message

**Comment by MadCatzAno** [comment]
![vyre_string](https://user-images.githubusercontent.com/11368028/99190665-21ad0000-2768-11eb-95cc-c543db0b085c.png)

ThievingPlugin.java:157:103 seems to have that string. Is the issue still there?

**Comment by billedwardz** [comment]
Naw it's good now, didn't see the email with xKylee's question, looks like someone on discord got them the success message though, figured they would close this on their own.
