### ISSUE TITLE
Equipment inspector broken

### ISSUE THREAD

**Issue by PowContent** [open-osrs/plugins#473]
The equipment inspector does not seem to work on all versions since 26/10/2020

**Comment by PowContent** [comment]
RCA Seems to be from 2b62746e07e51cf29393a8cddb193a2cb2468526

**Comment by zeruth** [comment]
https://github.com/open-osrs/runelite/pull/2838

**Comment by zeruth** [comment]
Thought for sure the plugin used the events that were disabled. seems that is not the case.
