### ISSUE TITLE
Loot tracker not working

### ISSUE THREAD

**Issue by olz123** [open-osrs/plugins#474]
loot tracker registers first kill ie tob chest, then doesnt register anything after that gets killed whether it being a 2nd tob, or i go kill a hill giant 
![image](https://user-images.githubusercontent.com/74269172/98729788-4fbec880-2393-11eb-9232-0732923a4bd5.png)

**Comment by zeruth** [comment]
Need to post your logs, sounds like it crashes somewhere and gets halted

**Comment by olz123** [comment]
> Need to post your logs, sounds like it crashes somewhere and gets halted

logs are found where?

**Comment by zeruth** [comment]
![image](https://user-images.githubusercontent.com/2943260/98734561-22145800-2370-11eb-91dd-82faca4a4374.png)
  
You can open the directory in the Info plugin as highlighted here, or find them in %USER%/.runelite/logs/  
  
Please verify that the log contains data before/after the plugin stops responding.

**Comment by olz123** [comment]
> ![image](https://user-images.githubusercontent.com/2943260/98734561-22145800-2370-11eb-91dd-82faca4a4374.png)
> 
> You can open the directory in the Info plugin as highlighted here, or find them in %USER%/.runelite/logs/
> 
> Please verify that the log contains data before/after the plugin stops responding.

![image](https://user-images.githubusercontent.com/74269172/98830746-aaf3c800-2432-11eb-8b8b-79a012168b0f.png)

this is what my log contains

**Comment by olz123** [comment]
[client.log](https://github.com/open-osrs/plugins/files/5526177/client.log)

**Comment by zeruth** [comment]
This has been fixed in https://github.com/open-osrs/runelite/pull/2856

**Comment by olz123** [comment]
any updates as to why it wouldn't be working?

**Comment by tr33s** [comment]
Are you compiling from source? I had this issue but updating [this](https://github.com/open-osrs/runelite/blob/master/http-api/src/main/java/net/runelite/http/api/loottracker/LootTrackerClient.java) in my project fixed it.
