### ISSUE TITLE
Quest Helper not highlighting the right dialogue options and often doesn't progress the quest. 

### ISSUE THREAD

**Issue by IliasWhoElse** [open-osrs/plugins#484]

**Comment by grian32** [comment]
It'd be nice for our developers if you could tell us which quests exactly this is happening on and send us some logs(do !logs in the discord if youre not sure how to go about sending the logs) if available.

**Comment by zeruth** [comment]
Upstream doesn't highlight most quest dialogues as is, so I doubt thats even a valid issue. As far as quests not progressing, yeah I'd like to know more about it, what quest, what step etc. We need information.

**Comment by weaman10** [comment]
i would say its pretty much every quest ive tried shows wrong directions dosent update/follow along with quest update marks wrong spots, sins of the father quest everything was broken pretty much

**Comment by PowContent** [comment]
I wouldnt say that its upstream. It seems to work fine in vanilla. As for getting the state of the quests, it does work if you force a plugin reload after every step and it will show you the next one. It just does not update automatically

**Comment by grian32** [comment]
> I wouldnt say that its upstream. It seems to work fine in vanilla. As for getting the state of the quests, it does work if you force a plugin reload after every step and it will show you the next one. It just does not update automatically

The meaning of the upstream label is that we need to pull from upstream to fix the issue.
