### ISSUE TITLE
Add inactivity logout timer together with logged in time in the report button box

### ISSUE THREAD

**Issue by permedd** [open-osrs/plugins#491]
read the whole suggestion there are **TWO** suggestions in one issue, I like the suggestion #2 more maybe have both and we choose what we want etc.

**1st suggestion**
An inactivity logout timer underneath he logged in timer.
![image](https://user-images.githubusercontent.com/37475765/101632002-25f1d380-3a1d-11eb-82ae-e954afec962d.png)
^ This image shows the normal report player section looks for me but I want it so I can see my 5:00 minute inactivity logout time as well so like this.

![image](https://user-images.githubusercontent.com/37475765/101632074-43bf3880-3a1d-11eb-827d-1e33a3dffeeb.png)
^ This is just a template on how I want it to look like.

![image](https://user-images.githubusercontent.com/37475765/101632130-56d20880-3a1d-11eb-867f-9dc72bdfe463.png)
^ And this is how I want it to look like at the end.

you can even have colours and colours means this.
colours meaning:
**Yellow** - is under attack (which will be a 20 minutes count down)
**Green** - is not under attack (which will be a 5 minutes count down)

This will be useful instead of having idle notification we can have a timer on the report player section, I think this will bring more people to use this client cos no other clients have these two together, like me I don't like using idle notification I rather see a timer.

**2nd suggestion**

Or maybe a Better suggestion.

We can use colours such as yellow and green which means these;
Yellow - is under attack (which will be a 20 minutes count down)
Green - is not under attack (which will be a 5 minutes count down)

maybe another suggestion for this is maybe you can do it like this
time online [how long left to logout]
**01:33:08 [00:04:59]**
I have added this because maybe the #1 suggestion having this might make the numbers super small, so I decided to change this one to a better option where it will not be on top of each other but next to each other examples showing below.

This is a better and updated version:

this is the new updated version which you might consider to add is this
![image](https://user-images.githubusercontent.com/37475765/101632467-da8bf500-3a1d-11eb-883e-2904b6b3b580.png)
^ like I said before
Yellow - is under attack (which will be a 20 minutes count down)

![image](https://user-images.githubusercontent.com/37475765/101632508-e8da1100-3a1d-11eb-9dac-3bbbaabbf522.png)
^ like I said before
Green - is not under attack (which will be a 5 minutes count down)

side note:
you might not even need the 6, 0s what I mean is this 00:00:00, you can just have 4 because if you are afking or not the max logout timer is 20minutes so you can just have it as 00:00 so example
**01:33:08 [04:59]** which this means that the player will log out in 4mins and 59 seconds and will go down to 00:00

**Comment by grian32** [comment]
Issues aren't for suggestions.
