### ISSUE TITLE
[ISSUE] OpenOSRS gives black box on launch.

### ISSUE THREAD

**Issue by Gittyhub123** [open-osrs/plugins#492]
When I launch OpenOSRS all I see is a black box. All the plugins are loaded, but the game doesn't load. 

It happened after the game update today.

I have tried disabling and removing the GPU plugin, but it doesn't help.

Any fixes for this?

**Comment by grian32** [comment]
Known issue caused by recent updates, it'll be worked on soon and there'll be a notification in the discord

**Comment by Gittyhub123** [comment]
Thank you for your quick reply @grian32. I don't have Discord so it's hard for me to find info. But thanks 👍
