### ISSUE TITLE
Chambers of Xeric Scouter/Points Counter

### ISSUE THREAD

**Issue by Jamonnin3** [open-osrs/plugins#532]
The overlay for the points counter should have some of the below options from runelite:
![image](https://user-images.githubusercontent.com/22843757/101644482-3a28d700-3a03-11eb-9caf-b80bdd08ee49.png)
Scouter Screenshot Hotkey (currently set to NumPad .)
Upload Scouting Screenshot (currently set to clipboard)

This allows you to simply press your hotkey and paste the scout overlay box into discord for fast scouts. Very convenient.

Display elapsed raid time is also nice, this shows how long the raid has gone for in the raid points overlay.

Current OpenOSRS Raids Points Overlay:
![image](https://user-images.githubusercontent.com/22843757/101644792-a0adf500-3a03-11eb-8e65-e8d93395e050.png)

Runelite's (with the options):
![image](https://user-images.githubusercontent.com/22843757/101644822-a99ec680-3a03-11eb-9354-b2a17a355c09.png)

This shows from top to bottom

Total: Total team points
RSN: Individual's points
(percentage of the whole team's points)
Time: Raid time elapsed
Party size: How many players are in your raiding party
Unique: Chances at a drop in your name
(Chances at a drop for you or your teammate)

These feature are the only features I've found lacking. Literally everything else is superior to Runelite and other clients in every way I have found. Thanks and I hope you look into adding these 👍

**Comment by grian32** [comment]
Most likely upstream related.
