### ISSUE TITLE
Pressing shift down

### ISSUE THREAD

**Issue by ReinierAarnink1996** [open-osrs/plugins#537]
good day, 

I like to constantly press down shift and use all functionality that come along with that. But currently I can only perform like one action with it before I have to release shift and press shift down again. I am new to the client and im used to the way runelite works.. for example left click filling rune pouches inside the bank interface would be nice.

i would like to withdraw prayer potions and shark and then eat and drink and then runecraft, come back and repeat without having to release shift and press down shift again.

Each time I withdraw an item from the bank I have to press down shift again for shift-functionality to work, for example each time I  withdraw a shark, I must first press down to be able to eat it, if I then withdraw a pray pot, I have to release and press shift down again, only then I can left click drink the pray pot. 

Kind regards,
Reinier

**Comment by xKylee** [comment]
I cannot reproduce, mine works as expected

**Comment by ImNoOSRS** [comment]
> I cannot reproduce, mine works as expected

He might have a weird keyboard driver, or another program which pressed/releases keys, so the issue probably is not OPRS/OSRS related.

I've never encourtered this either.

He should check:
https://w3c.github.io/uievents/tools/key-event-viewer.html

To see if the keyup event gets called randomly to make sure.
