### ISSUE TITLE
Screenshot-Include Overlays (off) still captures overlays

### ISSUE THREAD

**Issue by PowContent** [open-osrs/plugins#542]
When taking a screenshot, overlays are still included. From inspection of behaviour it seems like the screenshot is getting taken and the overlay frame is turned off for the frame after. Ideally the overlay check should be performed with the date trigger as that seems to work correctly.

**Comment by grian32** [comment]
This happens because of the respective plugin not including the functionality to hide it's overlays i think

**Comment by PowContent** [comment]
The overlay is turned off though for a tick. I have tested this with most plugins
