### ISSUE TITLE
Hiscores: Shows thermonucler smokedevil kc as zuk kc / upstream

### ISSUE THREAD

**Issue by grian32** [open-osrs/plugins#543]
![](https://cdn.discordapp.com/attachments/575130572955975691/798156740256202762/unknown.png)

Above is user `Smythy`

![](https://media.discordapp.net/attachments/575130572955975691/798157979505131570/unknown.png)

Above is user `Booke`

If you check their hiscores pages you can verify that their zuk kc is their thermonuclear devil kc, and that Smythy doesn't even have zuk kc on hiscores

Found by Alkharid Dealer#3049 on discord

According to Mat#9782 on discord this is caused by soul wars being added to the hiscores in  front of the bosses, and this shifting every other boss over by 1

Fixed by upstream

**Comment by zeruth** [comment]
This is because of a missing upstream for http-api's hiscores lookup. Soul wars was added.

**Comment by brianbis** [comment]
https://github.com/runelite/runelite/commit/0f17ecdaeadacc93cb4a16e6903b6208251ac852
