### ISSUE TITLE
BA Plugin Broken Post 20-01-21 Game Update

### ISSUE THREAD

**Issue by Koesa** [open-osrs/plugins#545]
- Timer does not display - Most likely causing:
- Calls to be invisible in the top right
- Removing incorrect calls from the horn removes all calls
- The de-prioritization of eggs on the ground for collector no longer works

That's all that I found from some collector rounds, likely there might be more issues from this. From what we know about the update, it makes sense that these are all the things impacted, however.

The model of eggs has changed and possibly what ever was reading the call current from the UI has been changed for the new white box that flashes.

**Comment by grian32** [comment]
Thanks for the issue, this is most likely going to be fixed when we do an upstream update(pulling changes from runelite).

**Comment by Koesa** [comment]
https://github.com/BegOsrs/Ba-minigame is seemingly an amalgamation of the original Runelite plugin and this one. He's been working on fixes, and might have more suitable solutions to this plugin sooner than Runelite. I'm not a developer at all tho so idk if it even helps.

**Comment by grian32** [comment]
> https://github.com/BegOsrs/Ba-minigame is seemingly an amalgamation of the original Runelite plugin and this one. He's been working on fixes, and might have more suitable solutions to this plugin sooner than Runelite. I'm not a developer at all tho so idk if it even helps.

AFAIK that's an rlhub plugin and needs to be manually ported to be used on OPRS.
