### ISSUE TITLE
Runecrafting pouch essence count doesn't work when filling from bank

### ISSUE THREAD

**Issue by siada** [open-osrs/plugins#57]
**Describe the bug**
In the latest version of osrs, they added the ability to change gear/interact with items/eat etc. without closing bank - one of these things is the ability to fill a runecrafting pouch without closing bank

The runecraft plugin however doesn't detect you filling if you do it while bank is open, if you fill pouch with bank closed it works

**To Reproduce**
1. Go to the bank
2. withdraw some essence and runecrafting pouches
3. fill runecrafting pouch from bank, pouch still reads 0

**Expected behavior**
1. Go to the bank
2. withdraw some essence and runecrafting pouches
3. runecrafting pouch reads the amount of essence in pouch

**Comment by xKylee** [comment]
This is the same upstream via the available plugin on the plugin hub.
