### ISSUE TITLE
Plugins build error.

### ISSUE THREAD

**Issue by NoLifeGaming** [open-osrs/plugins#579]
project :reminders
   > Could not find com.openosrs:runelite-client:4.9.5.
     Required by:
         project :reminders

I keep getting this error when trying to build plugins in intelliJ

Could not find com.openosrs:http-api:4.9.5.
Required by:
    project :reminders

**Comment by JumpIfZero** [comment]
This is not a support forum, please use the discord instead.

discord.gg/openosrs

**Comment by NoLifeGaming** [comment]
how do i get support on discord?

**Comment by xKylee** [comment]
Re-pull master
