### ISSUE TITLE
Loot tracker and boss timer not working at alchemical hydra

### ISSUE THREAD

**Issue by cloutwagon43** [open-osrs/plugins#616]
Loot tracker isnt tracking alchemical hydra kills, and the boss timer isnt showing respawn time

**Comment by Owain94** [comment]
@cloutwagon43 can you try to swap your update channel? eg. from stable to nightly or vice versa? We recently pushed an update that fixed other problems with the loot tracker. Changing channels forced the client to clear the cache, that way we can be sure you're on the latest version (including the fix mentioned above). After that could you check if the problem still exists?

**Comment by cloutwagon43** [comment]
Problem still exists after changing from stable to nightly, loot tracker seems to work in other places, im just having issues at hydra
