### ISSUE TITLE
friends exporter not working :(

### ISSUE THREAD

**Issue by RLrequest** [open-osrs/plugins#76]
I'm under the impression once you click export friends list, it was copied to clipboard and ready to paste, however after a few attempts, couple of restarts that appears not to be the case. heres my gif

https://i.imgur.com/85bC8ac.gifv

ty

**Comment by RLrequest** [comment]
goooood morning, any news? ty

**Comment by xKylee** [comment]
this is not a standard plugin that we provide. please report it to the owner of the plugin.
