### ISSUE TITLE
MES:ardounge cloak

### ISSUE THREAD

**Issue by Crystalknoct** [open-osrs/plugins#79]
Enabling ardougne cloak swap for equipment swapper causes the cape to always have what ever swap you have default stay enabled the entire time your current client is open. In some trial and error testing I noticed if you do this with the monastery teleport as your default it goes back to wear/remove fine however if you leave it on farm it says on farm and what ever you set it to afterwords until a restart.
https://i.imgur.com/fiJ250H.gifv

**Comment by xKylee** [comment]
i looked into this, i can see the problem, there is no removeswap. ill bundle it into the compliance update

**Comment by xKylee** [comment]
fixed in #83
