### ISSUE TITLE
Bronzemanmode

### ISSUE THREAD

**Issue by Kissaajuri** [open-osrs/plugins#86]
**Describe the Issue**
Going into any general market/other shop allows to unlock anything sold by players instantly which kinda neglects the idea of bronzemanmode. It would be a better option to not allow unlocking player sold items. Unlocking anything what is in stock by general should be only possible.

**To Reproduce**

    Go to General Market
    Open General Market -> You instantly unlock general stock but also all the player sold items aswell.

**Expected behavior**
Expected the plugin to only allow unlocking general stock items from npcs instead of player sold.

**Comment by xKylee** [comment]
resolved in latest merge.
