### ISSUE TITLE
Open online tracker broken

### ISSUE THREAD

**Issue by pratik-p** [open-osrs/plugins#88]
Looks like there is an exception thrown every time the 'open online tracker' option is clicked.

error: https://pastebin.com/CMUV7ngM

**Comment by xKylee** [comment]
can you close the client, relaunch and use nightly and see if this is resolved?

also, could we have a little bit more info such as what plugin are you using?

**Comment by pratik-p** [comment]
Relaunching didn't fix this.
This happens for the XpTracker plugin. Haven't experienced this for other plugins

**Comment by xKylee** [comment]
is this still an issue?

**Comment by pratik-p** [comment]
Sorry for the late reply, but it opens the tracker correctly without throwing an exception now.
